general:
  buildTool: "maven"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Acceptance:
    cloudFoundryDeploy: false
    uiVeri5ExecuteTests: false
  Release:
    cloudFoundryDeploy: false
    tmsUpload: false
steps:
  artifactPrepareVersion:
    versioningType: "library"
    dockerImage: "devxci/mbtci@sha256:5382a80333c0c1970d99327b30178bfa3f316e5f1e675639237b60e5eb5f8d00"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
